export type Breeding = {
  id: string | number;
  cowEarTag: string;
  cowName: string;
  heatDate: string;
  breedingMethod: string;
  breedingStatus: string;
  inseminationDate: string;
  bullName: string;
  bullMasterId?: number;
  inseminatorName: string;
  inseminatorMasterId?: number;
  transferPlannedDate: string;
  transferDate: string;
  transferCancelReason: string;
  embryoNumber: string;
  collectionDate: string;
  embryoType: string;
  donorCowName: string;
  donorCowEarTag: string;
  embryoSireName: string;
  embryoSireMasterId?: number;
  embryoGrade: string;
  strawNumber: string;
  supplierName: string;
  supplierMasterId?: number;
  transferTechnician: string;
  transferTechnicianMasterId?: number;
  nextHeatExpectedDate: string;
  pregnancyCheckExpectedDate: string;
  pregnancyCheckDate: string;
  pregnancyResult: string;
  recheckExpectedDate: string;
  expectedCalvingDate: string;
  estrusSigns?: string[];
  estrusSignsOther?: string;
  note: string;
  createdAt?: string;
  updatedAt?: string;
};

export type BreedingInput = Omit<Breeding, 'id' | 'createdAt' | 'updatedAt'>;
