export type CalfStatus = '販売予定' | '育成中' | '繁殖候補として留保' | '牛台帳へ移行済み' | '死亡・その他';
export type FeedingMethod = '人工哺育' | '母乳哺育' | '混合哺育';
export type WeaningStatus = '離乳前' | '離乳済み';

export type Calf = {
  id: number;
  calfNumber: string;
  identificationNumber: string;
  name: string;
  birthday: string;
  sex: string;
  motherName: string;
  startWeight: number;
  currentWeight: number;
  elapsedDays: number;
  milkAmount: number;
  starterAmount: number;
  feedingMethod: FeedingMethod;
  weaningPlannedDate: string;
  weaningDate: string;
  weaningStatus: WeaningStatus;
  weaningWeight: number;
  weaningStarterAmount: number;
  milkEndDate: string;
  managementStatus: CalfStatus;
  promotedCattleId?: number;
  promotedAt?: string;
  note: string;
  createdAt?: string;
  updatedAt?: string;
};

export type CalfInput = {
  calfNumber: string;
  identificationNumber: string;
  name: string;
  birthday: string;
  sex: string;
  motherName: string;
  startWeight: number;
  currentWeight: number;
  elapsedDays: number;
  milkAmount: number;
  starterAmount: number;
  feedingMethod: FeedingMethod;
  weaningPlannedDate: string;
  weaningDate: string;
  weaningStatus: WeaningStatus;
  weaningWeight: number;
  weaningStarterAmount: number;
  milkEndDate: string;
  managementStatus: CalfStatus;
  note: string;
};
