export type Treatment = {
  id: number;
  recordType?: string;
  targetNumber: string;
  targetName: string;
  symptom: string;
  diagnosis: string;
  diseaseMasterId?: number;
  treatmentProcedure?: string;
  treatmentProcedureMasterId?: number;
  hoofAbnormality?: string;
  nextScheduledDate?: string;
  treatmentDate: string;
  medicine: string;
  dosage: string;
  withdrawalEndDate: string;
  veterinarian: string;
  progress: string;
  note: string;
  createdAt?: string;
  updatedAt?: string;
};

export type TreatmentInput = {
  recordType?: string;
  targetNumber: string;
  targetName: string;
  symptom: string;
  diagnosis: string;
  diseaseMasterId?: number;
  treatmentProcedure?: string;
  treatmentProcedureMasterId?: number;
  hoofAbnormality?: string;
  nextScheduledDate?: string;
  treatmentDate: string;
  medicine: string;
  dosage: string;
  withdrawalEndDate: string;
  veterinarian: string;
  progress: string;
  note: string;
};
